### ISSUE TITLE
502 Bad Gateway Error

### ISSUE THREAD

**Issue by mirakrejci** [ONLYOFFICE/CommunityServer#106]
Hi,
our Community server (version 9.6.3-173) installed on Centos 7 (release 7.5.1804) frequently (several times a day) stops working (we can see 502 Bad Gateway Error at browser). After restarting monoserve service it is usually O.K.

corresponding log messages:

nginx.error.log:
[error] 1201#0: *16372 connect() to unix:/var/run/onlyoffice/onlyoffice.socket failed (11: Resource temporarily unavailable) while connecting to upstream, client: 127.0.0.1, server: , request: "POST /api/2
.0/batch.json HTTP/1.1", upstream: "fastcgi://unix:/var/run/onlyoffice/onlyoffice.socket:", host: "localhost"

web.socketio.08-01.log:
error: http://localhost/api/2.0/batch.json SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at Request.err [as _callback] (/var/www/onlyoffice/Services/ASC.Socket.IO/app/apiRequestManager.js:15:58)
    at Request.self.callback (/var/www/onlyoffice/Services/ASC.Socket.IO/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/onlyoffice/Services/ASC.Socket.IO/node_modules/request/request.js:1157:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/Services/ASC.Socket.IO/node_modules/request/request.js:1079:12)
    at IncomingMessage.g (events.js:292:16)

Could you help please?
Thanks.

Mira

**Comment by Carazyda** [comment]
Hello @mirakrejci What hardware do you use? Is it enough RAM? Swap? And count of active users on your portal?

**Comment by mirakrejci** [comment]
Hello,

OnlyOffice Community server is running on virtual machine with two virtual CPU's (Dell PE R730 with processors Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz), 4GB memory, 500MB swap (swap is not used).
It seems (according to "top", "sar" or "free" utilities) that memory is enough.
OnlyOffice we use in "test" mode. Count of active users are very low (usually 2-3).

Thank you.
Mira

**Comment by Carazyda** [comment]
Please try to increase RAM and swap, maybe it help you. And what is version of mono you installed (mono -V) ?

**Comment by mirakrejci** [comment]
Version of Mono is 5.12.0.301 (tarball Fri Jul 20 15:09:05 UTC 2018). So I try update to 5.14.0.177 and also try increase memory and swap.
Thanks.
Mira

**Comment by mirakrejci** [comment]
Hello,

Update Mono to 5.14.0.177 neither increasing memory to 8GB did not help. It was necessary to reboot server today. Restarting monoserve service had no effect.

Mira
