### ISSUE TITLE
Connecting Communityserver to Documentservice with UTM 9

### ISSUE THREAD

**Issue by Nandi90** [ONLYOFFICE/CommunityServer#126]
Hi Guys,

i have following problem. 
I have installed Community and Documentserver on 2 seperate Machines with Ubuntu 16.04 LTS 
Communityserver is working great but i can´t Connect to my Documentservice. Following error i found in the log

[2018-11-12 08:49:40.814] [ERROR] nodeJS - error downloadFile:url=https://domain.xy:443/storage/files_template/root/newdocuments/default/new.docx?X-REWRITER-URL=https%3a%2f%2fdomain.xy%3a443;attempt=3;code:UNABLE_TO_VERIFY_LEAF_SIGNATURE;connect:undefined;(id=conv_NhCwJeJ4dGVSK7Evtg8__docx)
Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:609:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:439:38)
[2018-11-12 13:19:22.379] [WARN] nodeJS - update cluster with 1 workers

i have no idea what can i do. i hope here is Anyone to help me 

thanks and best
Ferdinand

**Comment by Carazyda** [comment]
Hello @Nandi90  What is the error you got? How you connect document server, in portal settings(document service)? And specify in what log you have an error?

**Comment by Carazyda** [comment]
What error do you get when saving settings? Any errors in community server log, in particular web.api.log?

**Comment by Nandi90** [comment]
i become the following error in front of community server by save the settings 
Community server url: download,[object Object]

`2018-11-12 18:09:48,887 ERROR [Thread Pool Worker] ASC.Api - method error: https                                                                                                             ://local-ip/api/2.0/files/docservice.json?__=714464 - Server error
System.Exception: Community server url: download
  at ASC.Web.Files.Services.DocumentService.DocumentServiceConnector.CheckDocSer                                                                                                             viceUrl () [0x000b2] in <20d590741d8045fcb76883ad99649386>:0
  at ASC.Api.Documents.DocumentsApi.CheckDocServiceUrl (System.String docService                                                                                                             Url, System.String docServiceUrlInternal, System.String docServiceUrlPortal) [0x                                                                                                             00026] in <3e5734938f9b46a98a980088f5b656b3>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(Sys                                                                                                             tem.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.B                                                                                                             indingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] paramet                                                                                                             ers, System.Globalization.CultureInfo culture) [0x0003b] in <3833a6edf2074b959d3                                                                                                             dab898627f0ac>:0
`

**Comment by Carazyda** [comment]
This error means that address of community server is not respond from document server. Please check connection from document server to community.

**Comment by Nandi90** [comment]
witch way i can check this?

**Comment by Carazyda** [comment]
curl or ping community server address.

**Comment by Nandi90** [comment]
I have already done that before, in the 2 directions is available

**Comment by Carazyda** [comment]
and what is output of curl community server address?

**Comment by Nandi90** [comment]
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by Nandi90** [comment]
I have installed the certs in UTM9

**Comment by Carazyda** [comment]
Do you use a selfsigned certificates? Problem is in connection between two servers, not in Onlyoffice. You need configure your system to be connection between two servers. Or I recommend to you use docker in one server installation.

**Comment by Nandi90** [comment]
I didn´t found the Error. i have installed complet new and backup the old Database into the Docker version. Thanks for all help
