### ISSUE TITLE
 Table 'onlyoffice.dbip_location' doesn't exist

### ISSUE THREAD

**Issue by xbitlabs** [ONLYOFFICE/CommunityServer#160]
2019-05-23 11:40:05,307 ERROR [93] ASC.Geo - MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'onlyoffice.dbip_location' doesn't exist
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at ASC.Common.Data.AdoProxy.DbCommandProxy.ExecuteReader() in H:\CommunityServer-9.6.2\common\ASC.Common\Data\AdoProxy\DbCommandProxy.cs:line 103
   at ASC.Common.Data.DataExtensions.ExecuteListReader(IDbCommand command) in H:\CommunityServer-9.6.2\common\ASC.Common\Data\DataExtensions.cs:line 139
   at ASC.Common.Data.DataExtensions.ExecuteList(IDbCommand command, String sql, Object[] parameters) in H:\CommunityServer-9.6.2\common\ASC.Common\Data\DataExtensions.cs:line 133
   at ASC.Common.Data.DataExtensions.ExecuteList(IDbCommand command) in H:\CommunityServer-9.6.2\common\ASC.Common\Data\DataExtensions.cs:line 122
   at ASC.Common.Data.DataExtensions.ExecuteList(IDbCommand command, ISqlInstruction sql, ISqlDialect dialect) in H:\CommunityServer-9.6.2\common\ASC.Common\Data\DataExtensions.cs:line 199
   at ASC.Common.Data.DbManager.ExecuteList(ISqlInstruction sql) in H:\CommunityServer-9.6.2\common\ASC.Common\Data\DbManager.cs:line 222
   at ASC.Geolocation.GeolocationHelper.GetIPGeolocation(String ip) in H:\CommunityServer-9.6.2\common\ASC.Common\Geolocation\GeolocationHelper.cs:line 62

**Comment by Carazyda** [comment]
Hello @xbitlabs  Please describe more details? Where did you got this error?

**Comment by Carazyda** [comment]
Closed for a reason - there has been no activity for a long time.
