### ISSUE TITLE
 Error, download failed" message

### ISSUE THREAD

**Issue by reza-nasrollahi** [ONLYOFFICE/CommunityServer#348]
hi 
i install onlyoffice document server docker version on my ubunto 20 and 
i run onlyoffice community developer edition on win server 2019 
i can use example into docker but i cant connect to document server from  onlyoffice community and i got 
 download failed" message Error 
![Untitled](https://user-images.githubusercontent.com/50287768/138886902-4f068c50-e427-4bf6-8c26-37f3f9dc37fb.png)
and 
 
![index](https://user-images.githubusercontent.com/50287768/138887084-66478257-8d65-4927-a754-c5ca601d2727.jpg)
 please help me 
i know this is a common Error and Already resolved but i cant solve the problem
please help me

**Comment by reza-nasrollahi** [comment]
web.api:
2021-10-30 05:46:57,777 WARN [2250] ASC.Api - ASC cookie auth failed with cookie=BY+sDz0FF3aAbs0lVP5VqybgCPoRTXZTvvphXajCWROOr1wwRXJqi7IcxKcgSHTZar4alDjS7j2a+WuYOjXK8DTZ1JWRtK/IBa6PYukPC5p6Y98fuQgmczXnXWMa3Ug+YPyPrGeynJMO6sLx/Vq+Iw== 
2021-10-30 05:47:01,058 WARN [2249] ASC.Api - ASC cookie auth failed with cookie=BY+sDz0FF3aAbs0lVP5VqybgCPoRTXZTvvphXajCWROOr1wwRXJqi7IcxKcgSHTZar4alDjS7j2a+WuYOjXK8DTZ1JWRtK/IBa6PYukPC5p6Y98fuQgmczXnXWMa3Ug+YPyPrGeynJMO6sLx/Vq+Iw== 
2021-10-30 05:47:03,058 WARN [2205] ASC.Api - ASC cookie auth failed with cookie=BY+sDz0FF3aAbs0lVP5VqybgCPoRTXZTvvphXajCWROOr1wwRXJqi7IcxKcgSHTZar4alDjS7j2a+WuYOjXK8DTZ1JWRtK/IBa6PYukPC5p6Y98fuQgmczXnXWMa3Ug+YPyPrGeynJMO6sLx/Vq+Iw== 
2021-10-30 05:47:05,048 WARN [2205] ASC.Api - ASC cookie auth failed with cookie=BY+sDz0FF3aAbs0lVP5VqybgCPoRTXZTvvphXajCWROOr1wwRXJqi7IcxKcgSHTZar4alDjS7j2a+WuYOjXK8DTZ1JWRtK

web.file.log 

2021-10-29 16:52:35,704 ERROR [1323] ASC.Files - Converter DocService check error ASC.Web.Core.Files.DocumentService+DocumentServiceException: document signature
  at ASC.Web.Core.Files.DocumentService+DocumentServiceException.ProcessResponseError (System.String errorCode) [0x000eb] in <d7f02640224f496c8ba8635751acbbce>:0 
  at ASC.Web.Core.Files.DocumentService.GetResponseUri (System.String jsonDocumentResponse, System.String& responseUri) [0x00041] in <d7f02640224f496c8ba8635751acbbce>:0 
  at ASC.Web.Core.Files.DocumentService.GetConvertedUri (System.String documentConverterUrl, System.String documentUri, System.String fromExtension, System.String toExtension, System.String documentRevisionId, System.String password, ASC.Web.Core.Files.DocumentService+ThumbnailData thumbnail, ASC.Web.Core.Files.DocumentService+SpreadsheetLayout spreadsheetLayout, System.Boolean isAsync, System.String signatureSecret, System.String& convertedDocumentUri) [0x002e0] in <d7f02640224f496c8ba8635751acbbce>:0 
  at ASC.Web.Files.Services.DocumentService.DocumentServiceConnector.CheckDocServiceUrl () [0x00096] in <c5c00b7b8db34158a783fdf93d6ff129>:0 
 
web.api-system.log :
2021-10-12 07:03:56,866 DEBUG [1663] ASC.ApiSystem - Variant of correct auth:ASC QxJ5L6ik5uOEdl+OcLUUlvnaNb2GUcTV8ZEH+XmK0j0B7o/+qN8vAGBIZ6A0xQh/qQIDeh5arA+q0AXn3Lz2qkHTyKWJo/QXqwFmTHerjMiF7BZ79CpcTsJX0j9K/7J9uCQJZG3fkkHJ4yTdUhvPKA==:20211012070356:_-Eh5WwPlrnRsQb7nejnrcd_ijY1
2021-10-12 07:03:56,866 INFO [1663] ASC.ApiSystem - Auth success auth.allowskip
2021-10-12 07:03:57,134 DEBUG [1665] ASC.ApiSystem - Variant of correct auth:ASC QxJ5L6ik5uOEdl+OcLUUlvnaNb2GUcTV8ZEH+XmK0j0B7o/+qN8vAGBIZ6A0xQh/qQIDeh5arA+q0AXn3Lz2qkHTyKWJo/QXqwFmTHerjMiF7BZ79CpcTsJX0j9K/7J9uCQJZG3fkkHJ4yTdUhvPKA==:20211012070357:8s-hXJlVqFWNDKV3K46i-0adhzY1
2021-10-12 07:03:57,134 INFO [1665] ASC.ApiSystem - Auth success auth.allowskip
2021-10-12 07:10:00,506 DEBUG [1687] ASC.ApiSystem - Variant of correct auth:ASC QxJ5L6ik5uOEdl+OcLUUlvnaNb2GUcTV8ZEH+XmK0j0B7o/+qN8vAGBIZ6A0xQh/qQIDeh5arA+q0AXn3Lz2qkHTyKWJo/QXqwFmTHerjMiF7BZ79CpcTsJX0j9K/7J9uCQJZG3fkkHJ4yTdUhvPKA==:20211012071000:C8OpeIh7FBTdf3FKNnZlU8enUac1
2021-10-12 07:10:00,506 INFO [1687] ASC.ApiSystem - Auth success auth.allowskip
2021-10-12 07:10:00,705 DEBUG [1690] ASC.ApiSystem - Variant of correct auth:ASC QxJ5L6ik5uOEdl+OcLUUlvnaNb2GUcTV8ZEH+XmK0j0B7o/+qN8vAGBIZ6A0xQh/qQIDeh5arA+q0AXn3Lz2qkHTyKWJo/QXqwFmTHerjMiF7BZ79CpcTsJX0j9K/7J9uCQJZG3fkkHJ4yTdUhvPKA==:20211012071000:C8OpeIh7FBTdf3FKNnZlU8enUac1
2021-10-12 07:10:00,705 INFO [1690] ASC.ApiSystem - Auth success auth.allowskip

**Comment by Carazyda** [comment]
The error is here

> 2021-10-29 16:52:35,704 ERROR [1323] ASC.Files - Converter DocService check error ASC.Web.Core.Files.DocumentService+DocumentServiceException: document signature

You need to configured JWT between CommunityServer and DocumentServer, please read this [instruction](https://api.onlyoffice.com/editors/signature/). For CommunityServer you need change this in WebStudio\web.appsettings.config for keys `key="files.docservice.secret"` and `key="files.docservice.secret.header"`, and restart site of Onlyoffice in IIS.

**Comment by reza-nasrollahi** [comment]
The problem ..... was solved and now I have the first problem,  download fail



web.api:
2021-10-31 12:55:55,056 ERROR [21] ASC.Api - method error: http://localhost/api/2.0/files/docservice.json?__=63426 - Server error System.Exception: Converter url: download
   at ASC.Web.Files.Services.DocumentService.DocumentServiceConnector.CheckDocServiceUrl()
   at ASC.Api.Documents.DocumentsApi.CheckDocServiceUrl(String docServiceUrl, String docServiceUrlInternal, String docServiceUrlPortal)




web.log:

2021-10-31 12:56:42,460 ERROR [32] ASC - Service Error: Unable to connect to the remote server,    at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at ASC.Core.Notify.Signalr.SignalrServiceClient.MakeRequest(String method, Object data)
   at ASC.Core.Notify.Signalr.SignalrServiceClient.FilesChangeEditors(Int32 tenantId, String fileId, Boolean finish), No connection could be made because the target machine actively refused it 127.0.0.1:9899 
2021-10-31 12:57:04,564 ERROR [31] ASC - Service Error: Unable to connect to the remote server,    at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at ASC.Core.Notify.Signalr.SignalrServiceClient.MakeRequest(String method, Object data)
   at ASC.Core.Notify.Signalr.SignalrServiceClient.FilesChangeEditors(Int32 tenantId, String fileId, Boolean finish), No connection could be made because the target machine actively refused it 127.0.0.1:9899 
2021-10-31 14:51:04,388 ERROR [73] ASC - Service Error: Unable to connect to the remote server,    at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at ASC.Core.Notify.Signalr.SignalrServiceClient.MakeRequest(String method, Object data)
   at ASC.Core.Notify.Signalr.SignalrServiceClient.FilesChangeEditors(Int32 tenantId, String fileId, Boolean finish), No connection could be made because the target machine actively refused it 127.0.0.1:9899 
2021-10-31 15:07:19,376 ERROR [131] ASC - Service Error: Unable to connect to the remote server,    at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at ASC.Core.Notify.Signalr.SignalrServiceClient.MakeRequest(String method, Object data)
   at ASC.Core.Notify.Signalr.SignalrServiceClient.FilesChangeEditors(Int32 tenantId, String fileId, Boolean finish), No connection could be made because the target machine actively refused it 127.0.0.1:9899 




web.file :

2021-10-31 12:55:55,044 ERROR [21] ASC.Files - Converter DocService check error ASC.Web.Core.Files.DocumentService+DocumentServiceException: download
   at ASC.Web.Core.Files.DocumentService.DocumentServiceException.ProcessResponseError(String errorCode)
   at ASC.Web.Core.Files.DocumentService.GetResponseUri(String jsonDocumentResponse, String& responseUri)
   at ASC.Web.Core.Files.DocumentService.GetConvertedUri(String documentConverterUrl, String documentUri, String fromExtension, String toExtension, String documentRevisionId, String password, ThumbnailData thumbnail, SpreadsheetLayout spreadsheetLayout, Boolean isAsync, String signatureSecret, String& convertedDocumentUri)
   at ASC.Web.Files.Services.DocumentService.DocumentServiceConnector.CheckDocServiceUrl()

**Comment by Carazyda** [comment]
Problem is here. That means, DocumentServer cant resolve localhost address for the CommunityServer.
> 2021-10-31 12:55:55,056 ERROR [21] ASC.Api - method error: http://localhost/api/2.0/files/docservice.json?__=63426 - Server error System.Exception: Converter url: download

I already answered this problem

> You need to setup in CommunityServer address an ip that DocumentServer can resolve, not localhost.
