### ISSUE TITLE
Error open files > 40MB in format .xlsx

### ISSUE THREAD

**Issue by serinemsas** [ONLYOFFICE/CommunityServer#374]
Hi
![image](https://user-images.githubusercontent.com/36201244/168308093-edd9b06c-f6e0-406c-9e0b-3a6a0bb99368.png)

When trying to work with the file it doesn't work, error reloading the file, checking the log I find this error message:

[2022-05-12T16:42:24.004] [ERROR] nodeJS - error downloadFile:url=http://localhost:80/Products/Files/HttpHandlers/filehandler.ashx?action=stream&fileid=sbox-37-%7c%7cRELACION+DOCUMENTOS+2021+%23+2.xlsx&stream_auth=390087735768.UONVFXJRTUPJM22L12KATTKIXRSZJCORJJLOQTKHW&X-REWRITER-URL=https%3a%2f%2f192.168.1.248%3a443;attempt=3;code:null;connect:null;(id=DV7HQB8WMmOCLdRW_SBCF940JIo0pcQGTTGgELo_o1k_)
Error: Error response: statusCode:500; headers:{"server":"nginx","date":"Thu, 12 May 2022 21:42:24 GMT","content-type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","content-length":"53","connection":"keep-alive","content-disposition":"attachment; filename=\"RELACION DOCUMENTOS 2021 # 2.xlsx\"","x-aspnet-version":"4.0.30319","cache-control":"private","set-cookie":["ASP.NET_SessionId=D2B3FA4FFC2173C60C30A224; path=/; secure; HttpOnly"],"strict-transport-security":"max-age=63072000; includeSubDomains; preload"}; body:
The remote server returned an error: (404) Not Found.
    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Request.init.self.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
root@srvoffice:~#

I don't know what it means, please an explanation of this log, and what would be the possible solution?

greetings thx

**Comment by Carazyda** [comment]
Hello @serinemsas it means the file was not found. There probably isn't a physical copy on disk. Please check the file id, is it on the disk in the folder Data/Products/Files/? Does the problem reoccur only for this file or are there others?

**Comment by serinemsas** [comment]
Hi @carazyda, the folder is an owncloud connection on the same internal physical network between dedicated physical LAN ports, it only happens with large files, >20Mb according to tests, smaller files work perfectly.
