### ISSUE TITLE
Can't save documents 

### ISSUE THREAD

**Issue by gaalos** [ONLYOFFICE/CommunityServer#76]
Hello, i have a bug, i can create or open existing document, but i can't save it 

Logs : 

On my nextcloud : 
{"reqId":"37ocPMVvZ5nhCxzNwbnS","level":1,"time":"2017-09-28T12:19:23+00:00","remoteAddr":"10.0.0.9","user":"--","app":"onlyoffice","method":"POST","url":"\/apps\/onlyoffice\/track?doc=T1RpaXVYQnpqTEhmdW5KTC9wTEtrOUk5ZkoxeWJXWGFsaXhURjE1akFLVT0\/eyJmaWxlSWQiOjg4NTYxLCJvd25lcklkIjoidGJvdXJkZXQiLCJhY3Rpb24iOiJ0cmFjayJ9","message":"Track without url: 88561 status Corrupted","userAgent":"--","version":"12.0.2.0"}

On my Community : 
[2017-09-28 12:19:23.706] [ERROR] nodeJS - sendServerRequest error: docId = 8856115065995451;url = https://HIDEN/track?doc=T1RpaXVYQnpqTEhmdW5KTC9wTEtrOUk5ZkoxeWJXWGFsaXhURjE1akFLVT0/eyJmaWxlSWQiOjg4NTYxLCJvd25lcklkIjoidGJvdXJkZXQiLCJhY3Rpb24iOiJ0cmFjayJ9;data = {"key":"8856115065995451","status":3,"users":["tbourdet"],"actions":[{"type":0,"userid":"tbourdet"}],"lastsave":"2017-09-28T12:19:01.598Z","notmodified":false}
Error: Error response: statusCode:400 ;body:
{"message":"Url not found"}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:269:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

**Comment by alexanderonlyoffice** [comment]
Dublicate https://github.com/ONLYOFFICE/DocumentServer/issues/175
